### ISSUE TITLE
 django.db.utils.IntegrityError: null value in column "owner_id" of relation "main_build" violates not-null constraint

### ISSUE THREAD

**Issue by iarspider** [spack/spack-monitor#45]
Tried to use spack-monitor today. For now, I'm running in unauthenticated mode:
```
DISABLE_AUTHENTICATION: true
ENABLE_GITHUB_AUTH: null
```

But, when doing a monitored build, I get an error:
```
$ spack install --monitor --monitor-host=http://localhost --monitor-no-auth py-aiosqlite
==> Error: Internal Server Error

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>500: Error</title>
  <link href="https://fonts.googleapis.com/css?family=Courgette&display=swap" rel="stylesheet">
  <style>

body{
  font-family: 'Courgette', cursive;
  margin:0;
}

a:hover, a:focus {
 color: rebeccapurple !important;
}

#message {
  color: #00467f
  position: absolute;
  margin: auto;
  width: 50%;
  padding: 10px;
}
 </style>
</head>
<body>

<div id="message">
<img src="/static/img/spackmon-triangle-text-large.gif" style="width:90%" class="img-fluid img-center" />
<span style="font-size: 32px; font-weight:600; padding:20px">Your error has been logged, and please <a href="https://github.com/spack/spack-monitor/issues" target="_blank">open an issue</a> to ask for help.</a>
</div>
</body>
</html>
```

On the server side, I get [this error](https://gist.github.com/iarspider/c740a863da50dd97b300b5f6ed781747).

**Comment by iarspider** [comment]
And I have applied the [patches](https://github.com/spack/spack/pull/27511) to spack.

**Comment by vsoch** [comment]
You need to add your spckmon user and token to associate the build to someone. I’m not sure the server would work without authentication anymore (and I’d need to not allow that).

**Comment by vsoch** [comment]
And if we still allow unauthenticated builds I'd need to make a faux user to associate with. Would that be your preference?

**Comment by iarspider** [comment]
> You need to add your spckmon user and token to associate the build to someone. I’m not sure the server would work without authentication anymore (and I’d need to not allow that).

Ah. I see. 



> And if we still allow unauthenticated builds I'd need to make a faux user to associate with. Would that be your preference?

I can live with (legacy) auth. The server is going to be used for nightly builds anyway, not for team development.

**Comment by iarspider** [comment]
But removing `--monitor-no-auth` option at least for now is probably a good idea 😉

**Comment by vsoch** [comment]
@iarspider will do.

**Comment by vsoch** [comment]
okay here is a PR https://github.com/spack/spack/pull/27888

**Comment by iarspider** [comment]
Thanks!
